name: Release Charts

on: [push]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        
#      - name: Install Helm
#        uses: azure/setup-helm@v3
#        env:
#          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Prepare Helm Chart
        run: |
          python .github/workflows/prepare_helm_chart.py

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_PAGES_BRANCH: gh_pages_beta
          CR_GIT_REPO: helm-charts
          CR_PACKAGES_WITH_INDEX: "true"
          CR_SKIP_UPLOAD: "true"
          CR_RELEASE_NAME_TEAMPLATE: "helm-{{ .Version }}"